version: 2
updates:
  - package-ecosystem: nuget
    directory: /GW Launcher
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /site
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
